"""This module provides constants."""

from constants.assistant_info import (
    ADDRESSBOOK_INFO_TABLE_DATA,
    ADDRESSBOOK_INFO_TABLE_HEADERS,
    NOTEBOOK_INFO_TABLE_DATA,
    NOTEBOOK_INFO_TABLE_HEADERS,
)

__all__ = ["ADDRESSBOOK_INFO_TABLE_DATA", "ADDRESSBOOK_INFO_TABLE_HEADERS",
           "NOTEBOOK_INFO_TABLE_DATA", "NOTEBOOK_INFO_TABLE_HEADERS"]
